
export const PELICULAS_TYPES = {
  QUERIES: Symbol.for('QUERIES'),
  GET_ALL_PELICULAS: Symbol.for('GET_ALL_PELICULAS'),
  GET_RETRIEVE_PELICULAS: Symbol.for('GET_RETRIEVE_PELICULAS'),
  HTTP_SERVICE: Symbol.for('HTTP_SERVICE')
}
